In [3]:
import pandas as pd
import numpy as np

/home/akhil_/.local/lib/python3.12/site-packages/pandas/core/arrays/masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [9]:
!wget "https://drive.google.com/uc?export=download&id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_" -O mckinsey.csv

--2026-01-27 15:41:01--  https://drive.google.com/uc?export=download&id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_

Resolving drive.google.com (drive.google.com)... 142.250.77.110, 2404:6800:4007:807::200e
Connecting to drive.google.com (drive.google.com)|142.250.77.110|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_&export=download [following]
--2026-01-27 15:41:02--  https://drive.usercontent.google.com/download?id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.205.33, 2404:6800:4007:801::2001
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.205.33|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 83785 (82K) [application/octet-stream]
Saving to: ‘mckinsey.csv’

mckinsey.csv        100%[===================>]  81.82K  --.-KB/s    in 0.09s

2026-01-27 15:41:04 (869 KB/s) - ‘mckinsey.csv’ saved [83785/83785]

In [10]:
df = pd.read_csv("mckinsey.csv")

In [13]:
df.index = list(range(1, df.shape[0]+1)) #Explicit indexing from 1 to n

In [12]:
df

          country  year  population continent  life_exp     gdp_cap
1     Afghanistan  1952     8425333      Asia    28.801  779.445314
2     Afghanistan  1957     9240934      Asia    30.332  820.853030
3     Afghanistan  1962    10267083      Asia    31.997  853.100710
4     Afghanistan  1967    11537966      Asia    34.020  836.197138
5     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1700     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1701     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1702     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1703     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1704     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.index[1] # implicit index is giving explicit index value

2

In [22]:
df['implicit_index '] = df.index-1
ser = df[["country","implicit_index "]]
ser.head(20)

        country  implicit_index
1   Afghanistan                0
2   Afghanistan                1
3   Afghanistan                2
4   Afghanistan                3
5   Afghanistan                4
6   Afghanistan                5
7   Afghanistan                6
8   Afghanistan                7
9   Afghanistan                8
10  Afghanistan                9
11  Afghanistan               10
12  Afghanistan               11
13      Albania               12
14      Albania               13
15      Albania               14
16      Albania               15
17      Albania               16
18      Albania               17
19      Albania               18
20      Albania               19

In [ ]:
# Why to use explicit Index?
# 1. Easier Referencing
# 2. Better Readability
# 3. Customization
# 4. Data Integrity
# 5. Enhanced Functionality
# 6. Improved Performance
# 7. Consistency Across Datasets

Object `Index` not found.

In [23]:
df.index

Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
       ...
       1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704],
      dtype='int64', length=1704)

In [24]:
df = pd.read_csv('mckinsey.csv')

In [25]:
df.iloc[0:5]

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [26]:
df.loc[0:5]

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106
5  Afghanistan  1977    14880372      Asia    38.438  786.113360

In [27]:
df_temp = df.set_index("country")

In [28]:
df_temp.loc["Zimbabwe"]

          year  population continent  life_exp     gdp_cap
country
Zimbabwe  1952     3080907    Africa    48.451  406.884115
Zimbabwe  1957     3646340    Africa    50.469  518.764268
Zimbabwe  1962     4277736    Africa    52.358  527.272182
Zimbabwe  1967     4995432    Africa    53.995  569.795071
Zimbabwe  1972     5861135    Africa    55.635  799.362176
Zimbabwe  1977     6642107    Africa    57.674  685.587682
Zimbabwe  1982     7636524    Africa    60.363  788.855041
Zimbabwe  1987     9216418    Africa    62.351  706.157306
Zimbabwe  1992    10704340    Africa    60.377  693.420786
Zimbabwe  1997    11404948    Africa    46.809  792.449960
Zimbabwe  2002    11926563    Africa    39.989  672.038623
Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [31]:
df_temp.reset_index(inplace=True)

In [32]:
df_temp

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [42]:
# Addoing a new row to df_temp
new_row = {'country': 'Indiana', 'capital': 'Delhi', 'population': 123456, 'area': 7890}

In [43]:
newDF = pd.DataFrame([new_row])

In [44]:
df_joined = pd.concat([df,newDF])

In [45]:
df_joined

,country,year,population,continent,life_exp,gdp_cap,capital,area
0,Afghanistan,1952.0,8425333,Asia,28.801,779.445314,NaN,NaN
1,Afghanistan,1957.0,9240934,Asia,30.332,820.853030,NaN,NaN
2,Afghanistan,1962.0,10267083,Asia,31.997,853.100710,NaN,NaN
3,Afghanistan,1967.0,11537966,Asia,34.020,836.197138,NaN,NaN
4,Afghanistan,1972.0,13079460,Asia,36.088,739.981106,NaN,NaN
...,...,...,...,...,...,...,...,...
1700,Zimbabwe,1992.0,10704340,Africa,60.377,693.420786,NaN,NaN
1701,Zimbabwe,1997.0,11404948,Africa,46.809,792.449960,NaN,NaN
1702,Zimbabwe,2002.0,11926563,Africa,39.989,672.038623,NaN,NaN
1703,Zimbabwe,2007.0,12311143,Africa,43.487,469.709298,NaN,NaN
0,Indiana,NaN,123456,NaN,NaN,NaN,Delhi,7890.0

In [46]:
df_joined = pd.concat([df_temp, newDF], ignore_index=True)

In [47]:
df_joined

,country,year,population,continent,life_exp,gdp_cap,capital,area
0,Afghanistan,1952.0,8425333,Asia,28.801,779.445314,NaN,NaN
1,Afghanistan,1957.0,9240934,Asia,30.332,820.853030,NaN,NaN
2,Afghanistan,1962.0,10267083,Asia,31.997,853.100710,NaN,NaN
3,Afghanistan,1967.0,11537966,Asia,34.020,836.197138,NaN,NaN
4,Afghanistan,1972.0,13079460,Asia,36.088,739.981106,NaN,NaN
...,...,...,...,...,...,...,...,...
1700,Zimbabwe,1992.0,10704340,Africa,60.377,693.420786,NaN,NaN
1701,Zimbabwe,1997.0,11404948,Africa,46.809,792.449960,NaN,NaN
1702,Zimbabwe,2002.0,11926563,Africa,39.989,672.038623,NaN,NaN
1703,Zimbabwe,2007.0,12311143,Africa,43.487,469.709298,NaN,NaN
1704,Indiana,NaN,123456,NaN,NaN,NaN,Delhi,7890.0

In [48]:
df.tail(1)

       country  year  population continent  life_exp     gdp_cap
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [49]:
df_joined.iloc[-1]

country       Indiana
year              NaN
population     123456
continent         NaN
life_exp          NaN
gdp_cap           NaN
capital         Delhi
area           7890.0
Name: 1704, dtype: object

In [58]:
df.iloc[-1]["country"] = ["Japan", 2009, "Tokyo", 126300000, 377975]

/tmp/ipykernel_5197/1652038321.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1]["country"] = ["Japan", 2009, "Tokyo", 126300000, 377975]

In [59]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]