In [2]:
import numpy as np
import pandas as pd

In [3]:
a = np.arange(15)

In [4]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# # A, B, C: ---> Columns
# # 1, 2, 3, 4: ---> Rows

# Tabular Data is nothing but a matrix (Rows X Columns) # Pandas help us store heterogenous data

# Problem Statement

# DS @ McKinsey

- McKinsey wants to understand the relation between GDP per capita and life expectancy for their clients.
- The company has obtained data from various surveys conducted in different countries over several years.
- The acquired data includes information on -
  - Country
  - Population Size
  - Life Expectancy
  - GDP per Capita


- We have to analyse the data and draw inferences that are meaningful to the company.

In [5]:
!wget "https://drive.google.com/uc?export=download&id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_" -O mckinsey.csv

--2026-01-24 16:21:09--  https://drive.google.com/uc?export=download&id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_
Resolving drive.google.com (drive.google.com)... 142.250.183.174, 2404:6800:4007:815::200e
Connecting to drive.google.com (drive.google.com)|142.250.183.174|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_&export=download [following]
--2026-01-24 16:21:10--  https://drive.usercontent.google.com/download?id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.251.223.225, 2404:6800:4007:83a::2001
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.251.223.225|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 83785 (82K) [application/octet-stream]
Saving to: ‘mckinsey.csv’

mckinsey.csv        100%[===================>]  81.82K  --.-KB/s    in 0.1s

2026-01-24 16:21:12 (683 KB/s) - ‘mckinsey.csv’ saved [83785/83785]

In [6]:
df = pd.read_csv("mckinsey.csv")

In [ ]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [8]:
type(df)

pandas.core.frame.DataFrame

In [9]:
df.shape

(1704, 6)

In [11]:
country = df['country']

In [12]:
type(country)

pandas.core.series.Series

In [14]:
country

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [15]:
df2 = df[["country","year"]]

In [16]:
type(df2)

pandas.core.frame.DataFrame

In [17]:
df2

          country  year
0     Afghanistan  1952
1     Afghanistan  1957
2     Afghanistan  1962
3     Afghanistan  1967
4     Afghanistan  1972
...           ...   ...
1699     Zimbabwe  1987
1700     Zimbabwe  1992
1701     Zimbabwe  1997
1702     Zimbabwe  2002
1703     Zimbabwe  2007

[1704 rows x 2 columns]

# Few Specific Funtions in pandas

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     1704 non-null   object
 1   year        1704 non-null   int64
 2   population  1704 non-null   int64
 3   continent   1704 non-null   object
 4   life_exp    1704 non-null   float64
 5   gdp_cap     1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB

In [20]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [21]:
df.tail()

       country  year  population continent  life_exp     gdp_cap
1699  Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [22]:
df.shape[0]

1704

In [23]:
df.describe()

             year    population     life_exp        gdp_cap
count  1704.00000  1.704000e+03  1704.000000    1704.000000
mean   1979.50000  2.960121e+07    59.474439    7215.327081
std      17.26533  1.061579e+08    12.917107    9857.454543
min    1952.00000  6.001100e+04    23.599000     241.165876
25%    1965.75000  2.793664e+06    48.198000    1202.060309
50%    1979.50000  7.023596e+06    60.712500    3531.846988
75%    1993.25000  1.958522e+07    70.845500    9325.462346
max    2007.00000  1.318683e+09    82.603000  113523.132900

In [24]:
basic_stats_df = df.describe(include='object')

In [25]:
basic_stats_df

            country continent
count          1704      1704
unique          142         5
top     Afghanistan    Africa
freq             12       624

In [27]:
df["country"].value_counts()

country
Afghanistan          12
Pakistan             12
New Zealand          12
Nicaragua            12
Niger                12
                     ..
Eritrea              12
Equatorial Guinea    12
El Salvador          12
Egypt                12
Zimbabwe             12
Name: count, Length: 142, dtype: int64

In [28]:
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [29]:
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [31]:
df["country"].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
       'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Czech Republic',
       'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia',
       'Finland', 'France', 'Gabon', 'Gambia', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti',
       'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea, Dem. Rep.',
       'Korea, Rep.', 'Kuwait', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Madagascar', 'Malawi', 'Malaysia', 'Mali', 'Mauritania',
       'Mauritius', 'Mexico', 'Mongolia', 'Montenegro', 'Morocco',
       'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman',
       'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Puerto Rico', 'Reunion', 'Romania', 'Rwanda',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia',
       'Somalia', 'South Africa', 'Spain', 'Sri Lanka', 'Sudan',
       'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tanzania', 'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Uganda', 'United Kingdom', 'United States', 'Uruguay',
       'Venezuela', 'Vietnam', 'West Bank and Gaza', 'Yemen, Rep.',
       'Zambia', 'Zimbabwe'], dtype=object)

In [33]:
df['country'].nunique()

142

In [34]:
len(df['country'].unique())

142

In [35]:
df["country"].unique().shape[0]

142

In [36]:
df["country"].value_counts()

country
Afghanistan          12
Pakistan             12
New Zealand          12
Nicaragua            12
Niger                12
                     ..
Eritrea              12
Equatorial Guinea    12
El Salvador          12
Egypt                12
Zimbabwe             12
Name: count, Length: 142, dtype: int64

In [37]:
df["country"].value_counts().reset_index()

               country  count
0          Afghanistan     12
1             Pakistan     12
2          New Zealand     12
3            Nicaragua     12
4                Niger     12
..                 ...    ...
137            Eritrea     12
138  Equatorial Guinea     12
139        El Salvador     12
140              Egypt     12
141           Zimbabwe     12

[142 rows x 2 columns]

In [40]:
# from pupulation i want to make it as population 
df = df.rename(columns={"population": "Population"})

In [41]:
df

          country  year  Population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [43]:
df.rename(columns={"Population": "population"}, inplace=True)

In [44]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

### Dropping columns

In [47]:
df.drop(columns="life_exp")

          country  year  population     gdp_cap
0     Afghanistan  1952     8425333  779.445314
1     Afghanistan  1957     9240934  820.853030
2     Afghanistan  1962    10267083  853.100710
3     Afghanistan  1967    11537966  836.197138
4     Afghanistan  1972    13079460  739.981106
...           ...   ...         ...         ...
1699     Zimbabwe  1987     9216418  706.157306
1700     Zimbabwe  1992    10704340  693.420786
1701     Zimbabwe  1997    11404948  792.449960
1702     Zimbabwe  2002    11926563  672.038623
1703     Zimbabwe  2007    12311143  469.709298

[1704 rows x 4 columns]

In [46]:
df.drop(columns="continent",inplace=True)

In [48]:
df

          country  year  population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [49]:
df.drop(columns=["country","year"])

      population  life_exp     gdp_cap
0        8425333    28.801  779.445314
1        9240934    30.332  820.853030
2       10267083    31.997  853.100710
3       11537966    34.020  836.197138
4       13079460    36.088  739.981106
...          ...       ...         ...
1699     9216418    62.351  706.157306
1700    10704340    60.377  693.420786
1701    11404948    46.809  792.449960
1702    11926563    39.989  672.038623
1703    12311143    43.487  469.709298

[1704 rows x 3 columns]

In [55]:
df.drop("life_exp",axis=1)

          country  year  population     gdp_cap  after_10_year           GDP
0     Afghanistan  1952     8425333  779.445314           1962  6.567086e+09
1     Afghanistan  1957     9240934  820.853030           1967  7.585449e+09
2     Afghanistan  1962    10267083  853.100710           1972  8.758856e+09
3     Afghanistan  1967    11537966  836.197138           1977  9.648014e+09
4     Afghanistan  1972    13079460  739.981106           1982  9.678553e+09
...           ...   ...         ...         ...            ...           ...
1699     Zimbabwe  1987     9216418  706.157306           1997  6.508241e+09
1700     Zimbabwe  1992    10704340  693.420786           2002  7.422612e+09
1701     Zimbabwe  1997    11404948  792.449960           2007  9.037851e+09
1702     Zimbabwe  2002    11926563  672.038623           2012  8.015111e+09
1703     Zimbabwe  2007    12311143  469.709298           2017  5.782658e+09

[1704 rows x 6 columns]

In [50]:
df["after_10_year"] = df["year"]+10

In [56]:
df

,country,year,population,life_exp,gdp_cap,after_10_year,GDP
0,Afghanistan,1952,8425333,28.801,779.445314,1962,6.567086e+09
1,Afghanistan,1957,9240934,30.332,820.853030,1967,7.585449e+09
2,Afghanistan,1962,10267083,31.997,853.100710,1972,8.758856e+09
3,Afghanistan,1967,11537966,34.020,836.197138,1977,9.648014e+09
4,Afghanistan,1972,13079460,36.088,739.981106,1982,9.678553e+09
...,...,...,...,...,...,...,...
1699,Zimbabwe,1987,9216418,62.351,706.157306,1997,6.508241e+09
1700,Zimbabwe,1992,10704340,60.377,693.420786,2002,7.422612e+09
1701,Zimbabwe,1997,11404948,46.809,792.449960,2007,9.037851e+09
1702,Zimbabwe,2002,11926563,39.989,672.038623,2012,8.015111e+09
1703,Zimbabwe,2007,12311143,43.487,469.709298,2017,5.782658e+09

In [53]:
df["GDP"] = df["gdp_cap"] * df["population"]

In [54]:
df

,country,year,population,life_exp,gdp_cap,after_10_year,GDP
0,Afghanistan,1952,8425333,28.801,779.445314,1962,6.567086e+09
1,Afghanistan,1957,9240934,30.332,820.853030,1967,7.585449e+09
2,Afghanistan,1962,10267083,31.997,853.100710,1972,8.758856e+09
3,Afghanistan,1967,11537966,34.020,836.197138,1977,9.648014e+09
4,Afghanistan,1972,13079460,36.088,739.981106,1982,9.678553e+09
...,...,...,...,...,...,...,...
1699,Zimbabwe,1987,9216418,62.351,706.157306,1997,6.508241e+09
1700,Zimbabwe,1992,10704340,60.377,693.420786,2002,7.422612e+09
1701,Zimbabwe,1997,11404948,46.809,792.449960,2007,9.037851e+09
1702,Zimbabwe,2002,11926563,39.989,672.038623,2012,8.015111e+09
1703,Zimbabwe,2007,12311143,43.487,469.709298,2017,5.782658e+09